apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/generated/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/generated/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: account-service
    spec:
      containers:
        - env:
            - name: DATABASE_PATH
              value: /data/account.db
            - name: LOG_LEVEL
              value: INFO
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_SERVICE_NAME
              value: account-service
            - name: RABBITMQ_URL
              value: amqp://challenge:challenge@rabbitmq:5672/%2F
          image: account-service:latest
          imagePullPolicy: IfNotPresent
          name: account-service
          ports:
            - containerPort: 8002
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: account-data
      restartPolicy: Always
      volumes:
        - name: account-data
          persistentVolumeClaim:
            claimName: account-data
